-- 등록된 계정들을 확인하기
SELECT USERNAME
FROM DBA_USERS;

-- DBA_USERS 라는 테이블에는 어떤 컬럼이 있을까
DESC DBA_USERS;

-- 어떤 부분에 락이 걸려있는가
SELECT USERNAME, ACCOUNT_STATUS 
FROM DBA_USERS;

-- SCOTT 계정에 비번은 !dkdlxl1234로 생성
-- 12버젼부터는 무조건 USER명에 C##을 붙여줘야 한다
CREATE USER C##SCOTT IDENTIFIED BY "!dkdlxl1234";

DROP USER C##SCOTT;

-- 이래야 계정생성 시 앞에 c##을 제외해도 생성 가능
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE; -- SESSION을 변경

-- C##을 빼고 다시 계정을 생성해보자
CREATE USER SCOTT IDENTIFIED BY "!dkdlxl1234";

-- ANGEL/a1234
CREATE USER ANGEL IDENTIFIED BY "a1234";

-- sid 조회
SELECT INSTANCE FROM V$THREAD;

-- ANGEL 계정에 LOCK을 설정
ALTER USER ANGEL ACCOUNT LOCK;

SELECT USERNAME, ACCOUNT_STATUS
FROM DBA_USERS
WHERE USERNAME = 'ANGEL';

ALTER USER ANGEL ACCOUNT UNLOCK;

-- 권한 설정
-- GRANT 점속할 수 있는 권한
-- RESOURCE 데이터 관리 가능 권한
GRANT CONNECT, RESOURCE TO ANGEL;
GRANT CONNECT, RESOURCE TO SCOTT;

-- 생성된 계정에서 테이블을 생성하고
-- 데이터를 추가하려고 하면 TABLE SPACE에 대한 오류 생성
-- TABLE SPACE를 UNLIMIT으로 설정 (SYS 계정에서만 가능)
ALTER USER ANGEL DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER SCOTT DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- ANGEL의 비번을 a1234 -> pw1234 설정할 때 
ALTER USER ANGEL IDENTIFIED BY pw1234;
